#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Hook to run after EDITOR exits, following `git commit' $
# $Copyright: 2015-2017 The FrauBSD Project. All rights reserved. $
# $GitHub: kubernetes-bootstrap.git .git-hooks/commit-msg master 2017-09-05 11:13:45 +0000 unknown $
#
############################################################ INFORMATION
#
# System requirements: awk(1) git(1) xargs(1)
# See also: .git-filters/keywords
#
############################################################ MAIN

DEBUG(){ [ ! "$DEBUG" ] || echo "DEBUG: $*"; }
DEBUG "$0 $*"

# Test the commit message file for content (indicating commit not aborted)
DEBUG "Checking commit message..."
awk '!/^[[:space:]]*(#|$)/{exit found++}END{exit !found}' "$1" &&
	{ DEBUG "Committing!"; exit 0; }
DEBUG "Commit aborted!"

# Commit aborted: Unset keywords in modified text-files
DEBUG "Keyword modifications..."
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -0 .git-filters/keywords -d --
DEBUG "End List"

# Update the staging files
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -0 git add -u -v --

################################################################################
# END
################################################################################
