#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Hook to run before `git commit' $
# $Copyright: 2015-2017 The FrauBSD Project. All rights reserved. $
# $GitHub: freebsd-docker/kubernetes-bootstrap.git .git-hooks/pre-commit 2017-09-05 18:27:52 +0000 freebsdfrau $
#
############################################################ INFORMATION
#
# System requirements: git(1) xargs(1)
# See also: .git-filters/keywords
#
############################################################ MAIN

DEBUG(){ [ ! "$DEBUG" ] || echo "DEBUG: $*"; }
DEBUG "$0 $*"

# Set keywords in modified text-files prior to commit
DEBUG "Keyword modifications..."
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -0 .git-filters/keywords --
DEBUG "End List"

# Update the staging files
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -0 git add -u -v --

################################################################################
# END
################################################################################
